# Generated by Django 5.0.2 on 2025-05-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccAdvances',
            fields=[
                ('slno', models.DecimalField(decimal_places=0, max_digits=12, primary_key=True, serialize=False)),
                ('account', models.CharField(blank=True, max_length=30, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
            ],
        ),
    ]
